// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDJ0ypfN7ULgwTP5o4z_FkuCsy6xO2ZQM',
    appId: '1:520180584514:android:8aa01255bf1f617c0b5ddb',
    messagingSenderId: '520180584514',
    projectId: 'managing-the-projects',
    storageBucket: 'managing-the-projects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1BO_h9_tTSsNfVcbOgzsHAoVdHgSuieE',
    appId: '1:520180584514:ios:ae17632242d4a2220b5ddb',
    messagingSenderId: '520180584514',
    projectId: 'managing-the-projects',
    storageBucket: 'managing-the-projects.appspot.com',
    androidClientId: '520180584514-78m55d35ui7hmh0jg2aitmvs2g0bn83p.apps.googleusercontent.com',
    iosClientId: '520180584514-66psgrhedpnqrkcpss346or5rr5bqsvc.apps.googleusercontent.com',
    iosBundleId: 'com.honsoncooky.managingTheProjects',
  );
}
